/** Declaration file generated by dts-gen */

export = logger

declare function logger(opts: any, stream: any): any

declare namespace logger {
  const prototype: {}

  namespace Serializers {
    function err(err: any): any

    function req(req: any): any

    function res(res: any): any

    namespace err {
      const prototype: {}
    }

    namespace req {
      const prototype: {}
    }

    namespace res {
      const prototype: {}
    }
  }
}
