/** Declaration file generated by dts-gen */

export function heroku(hex: any): any;

export function hex(length: any): void;

export function humanized(words: any): any;

export function numeric(digits: any): any;

export function pokemon(hex: any): any;

export function shortStamp(): void;

export function timeStamp(): void;

export function v4(): void;

export namespace heroku {
    const prototype: {
    };

}

export namespace humanized {
    const prototype: {
    };

}

export namespace numeric {
    const prototype: {
    };

}

export namespace pokemon {
    const prototype: {
    };

}

