/** Declaration file generated by dts-gen */

export = CactusServer

declare class CactusServer {
  constructor(...args: any[])

  listen(...args: any[]): void

  static emptyResponse(...args: any[]): void

  static logErrors(...args: any[]): void

  static notFoundResponse(...args: any[]): void

  static notImplementedResponse(...args: any[]): void

  static notifyErrors(...args: any[]): void
}

declare namespace CactusServer {

}
